### PR TITLE
Fix folderstructure

### PR DESCRIPTION
**Pull request by schlingling**
Fixed folderstructure, removed examples, added folders for structuring frontend & backend

### CODE REVIEW

**Comment by phildree** [comment]
Thank you for adjusting the folder structure @schlingling! :)

I might have a proposition for a naming that might be more understandable (at least for me => maybe the other DEVs cloud and a comment with their oppinion):
I would create one folder called CLI (or something along those lines) and one folder called backend. IMHO this would make it more clear, that the CLI component is seperated from the backend, where the logik for handling the different blockchains resides.
If think this would be very nice, especially considering the possible future, in which the backend components might also be reused to build a web frontend instead of a CLI or even reused by our clients at SHS.
Best regards, 
Philipp

**Comment by schlingling** [comment]
> Thank you for adjusting the folder structure @schlingling! :)
> 
> I might have a proposition for a naming that might be more understandable (at least for me => maybe the other DEVs cloud add a comment with their oppinion): I would create one folder called CLI (or something along those lines) and one folder called backend. IMHO this would make it more clear, that the CLI component is seperated from the backend, where the logik for handling the different blockchains resides. If think this would be very nice, especially considering the possible future, in which the backend components might also be reused to build a web frontend instead of a CLI (or even reused by our clients at SHS). Best regards, Philipp

@phildree I TOTALLY AGREE with your point! We should change ne naming, as you requested!

**Comment by tawfeeka** [comment]
I agree @phildree

**Comment by schlingling** [comment]
@phildree @tawfeeka Changed the name and pushed it again. I will merge to main now. Please approve the PR

**Review by MPSebastian — APPROVED** [review]

**Pull request merged**
