### PR TITLE
documentation

### PR DESCRIPTION
**Pull request by lukas-rotsching**
is it ok if we just put the link to the github wiki here or do do we need to put all the wikis source .md files here as well?

### CODE REVIEW

**Comment by schlingling** [comment]
> 
@lukas-rotsching 
We need for every Doc-Type a separate file with correct naming (see in HW-Document). I will fix it and commit this here :) 
image

**Comment by schlingling** [comment]
@lukas-rotsching Added the files.

@Noah-Kurz @lukaswolfrum I also copied the files to the folder sprint06 with correct naming.

**Review by schlingling — APPROVED** [review]

**Comment by lukaswolfrum** [comment]
great thanks a lot! @schlingling

**Review by lukaswolfrum — APPROVED** [review]

**Comment by lukaswolfrum** [comment]
Oh, I thought after you started creating the Docs and I haven't heard anything earlier that you created it already. 

For me it would actually make more sense if one of you DEVs would start creating it and I can review it later and add my comments. Especially as I am still unsure where I can find the current updated code base.

**Review by phildree — APPROVED** [review]

**Pull request merged**
