### PR TITLE
Cli

### PR DESCRIPTION
**Pull request by tawfeeka**
This should be the final pull request for the mid term release.
I updated the frontend-middleware connection, so the program fulfills the whole functionality shown in the .pptx file.

### CODE REVIEW

**Review by MPSebastian — APPROVED** [review]
looks good!

**Review by lukas-rotsching — APPROVED** [review]
👌

**Review by phildree — APPROVED** [review]
Looks good, please merge so that I can create our RC

**Review by schlingling — APPROVED** [review]
🚀

**Comment by phildree** [comment]
Actually there seems to be a problem. I checked out the branch and tested it, and found out that somehow the users_private_key is not passed to the backend when creating a contract:
Screenshot_2022-06-08_07-55-59
Screenshot_2022-06-08_07-56-22

I can have a look at it and try to fix this or you can just add this parameter where it is missing, if you already now where the cause for this problem is.

Should be quite easy (my guess is that this happens because we changed our middlewares data structures but did not change the way the parameters are passend onto our backend)

**Pull request merged**
