### PR TITLE
add select Wallet Command to fix #50

### LINKED ISSUE #50: "Add wallet" feature in CLI
## User story
1. As a user 
2. I want / need to connect my wallet over the CLI
3. So that i can pay gas fees and mint NFTs

## Acceptance criteria
* "Add wallet" screen opens when "Add wallet" is selected in the "Select Wallet" menu
* "Add wallet" screen allows input from the user to create a new wallet
* Added wallet appears in the "select wallet" menu

## Definition of done (DoD)
* A Feature is Done when all its Acceptance criterias are fulfilled
* A Feauture is Done when the code has been peer reviewed from the dedicated team
* A Feature is Done when it has been tested
* A Feature is Done when its core functionality has been commented properly
* A Feature is Done when it can be fully integrated into the main branch without negative side effect

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

### PR DESCRIPTION
**Pull request by tawfeeka**
Signed-off-by: Tawfeek Al-Sheikh <tawfeek.alsheikh@gmail.com>

### CODE REVIEW

**Review by lukas-rotsching — COMMENTED** [review]
approved

**Review by MPSebastian — APPROVED** [review]

**Review by laila-rin — APPROVED** [review]
looks good!

**Review by schlingling — CHANGES_REQUESTED** [review]
@tawfeeka This looks very good! Please merge at a first PR #60 which fixes our CI-Pipeline. After merging #60 you can merge this one and the pipeline will not fail anymore! 👍 

When you have merged #60,  can give you an approval for this PR.

**Review by schlingling — APPROVED** [review]

**Comment by schlingling** [comment]
Ready to merge @tawfeeka

**Review by phildree — APPROVED** [review]

**Pull request merged**
